spring:
  application:
    name: mongo-redis-helper
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodb:27017/jenkins-helper}
    redis:
      url: ${REDIS_URI:redis://localhost:6379}
  jackson:
    property-naming-strategy: SNAKE_CASE
  threads:
    virtual:
      enabled: true


server:
  port: 8080

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}|%X{appName}|%thread|%level|%logger.%M|%X{uid}|%X{uri}|%X{method}|%msg%n"
  level:
    root: INFO
    io.github.abhishekghosh: ${APPLICATION_LOGGING_LEVEL:debug}
