# Specify the platform explicitly for ARM Macs to emulate amd64
FROM --platform=linux/amd64 splunk/splunk:latest

# Set environment variables for Splunk configuration
ENV SPLUNK_START_ARGS="--accept-license"
ENV SPLUNK_PASSWORD="yourpassword"

# Expose necessary ports
EXPOSE 8000 8089 9997

# Start Splunk service
CMD ["/sbin/entrypoint.sh", "start"]