apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "cart-service.selectorLabels" . | nindent 4 }}
