apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-service.fullname" . }}-secret
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_ROOT_USER: {{ .Values.secrets.MONGO_ROOT_USER | b64enc | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.MONGO_ROOT_PASSWORD | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
