apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inventory-service.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: commercesphere.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "inventory-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
