replicaCount: 2

image:
  repository: commercesphere/identity-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 15
    periodSeconds: 5

env:
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JWT_EXPIRATION_MS: "3600000"
  JWT_REFRESH_EXPIRATION_MS: "2592000000"

secrets:
  MONGO_ROOT_USER: root
  MONGO_ROOT_PASSWORD: rootroot
  REDIS_PASSWORD: rootroot
  JWT_SECRET: commerce-sphere-jwt-secret-key-that-is-at-least-256-bits-long-for-hs256

ingress:
  enabled: true
  className: nginx
  host: commercesphere.local
  path: /api/auth
  pathType: Prefix
