spring:
  data:
    mongodb:
      uri: mongodb://root:rootroot@mongodb:27017/auth_db?authSource=admin
    redis:
      host: redis
      port: 6379
      password: rootroot
  mail:
    host: mailpit
    port: 1025
