services:
  splunk-helper:
    container_name: splunk-helper
    image: abhishek1009/splunk-helper:latest
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: src
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/splunk?authSource=admin
    ports:
      - "8080:8080"
    networks:
      - splunk-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - splunk-data:/data/db
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "27017:27017"
    networks:
      - splunk-network
#  splunk:
#    build:
#      context: .
#      dockerfile: Dockerfile-splunk
#    container_name: splunk-arm
#    ports:
#      - "8000:8000"  # Splunk Web UI
#      - "8088:8088"  # HTTP Event Collector (HEC)
#      - "9997:9997"  # Forwarding port
#    environment:
#      SPLUNK_START_ARGS: "--accept-license"
#      SPLUNK_PASSWORD: "changeme"
#      SPLUNK_HEC_TOKEN: "your-hec-token"
#    restart: unless-stopped
#    networks:
#      - splunk-network
#    volumes:
#      - splunk-data:/opt/splunk/var


volumes:
  splunk-data:
    driver: local

networks:
  splunk-network:
    driver: bridge