spring:
  application:
    name: jpa-helper
  profiles:
    active: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: false # flyway is disabled as postgres of this version is not supported by flyway
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}|%X{appName}|%thread|%level|%logger.%M|%X{uid}|%X{uri}|%X{method}|%msg%n"
  level:
    root: INFO
    io.github.abhishekghosh: ${APPLICATION_LOGGING_LEVEL:debug}
