package io.github.abhishekghoshh.aws.dynamodb.product;


import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.util.ArrayList;
import java.util.List;

@DynamoDbBean
public class Product {


    private String id;
    private String name;
    private double price;
    private List<String> tags = new ArrayList<>();
    private AdditionalInfo additionalInfo;


    public Product() {
    }

    public Product(String name, double price, List<String> tags, AdditionalInfo additionalInfo) {
        this.name = name;
        this.price = price;
        this.tags = tags;
        this.additionalInfo = additionalInfo;
    }


    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    @DynamoDbSortKey
    public double getPrice() {
        return price;
    }

    public List<String> getTags() {
        return tags;
    }

    public AdditionalInfo getAdditionalInfo() {
        return additionalInfo;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public void setAdditionalInfo(AdditionalInfo additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
}