version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jpa-helper
    ports:
      - "5432:5432"
    networks:
      - jpa-helper
    volumes:
      - jpa-helper:/var/lib/postgresql/data

  jpa-tutorial-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jpa-helper
    image: abhishek1009/jpa-tutorial
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - jpa-helper
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: jpa-helper



volumes:
  jpa-helper:

networks:
  jpa-helper: