apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "loansphere.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_USERNAME: {{ .Values.mongodb.username | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
